### ISSUE TITLE
amCharts usage terms may not be compatible with open source projects

### ISSUE THREAD

**Issue by brylie** [synw/django-chartmodels#1]
The amCharts licensing model may preclude it from being released as part of an open source project/module. Based on discussion in the `django-chartflo` project, it may be advisable to replace amCharts with a fully open-source charting library (such as Chart.js).

**Comment by synw** [comment]
You are right. The priority is to move away from Amcharts, which is on top of the priorities list for `django-chartflo`: [reference](https://github.com/synw/django-chartflo/issues/1)

After this I'll update and cleanup this old module
