### ISSUE TITLE
Consider replacing pie chart and table with bar chart

### ISSUE THREAD

**Issue by brylie** [synw/django-chartmodels#2]
While pie charts and tables might not always be bad, there are alternatives that are easier to perceive and understand. Specifically, bar charts are common and easy for us to understand.

Consider replacing the pie chart and table view with a basic bar chart.

![pie chart and table](https://camo.githubusercontent.com/9afd41697d1673d6c037c8a9fdb86fdba586fe6b/68747470733a2f2f7261772e6769746875622e636f6d2f73796e772f646a616e676f2d63686172746d6f64656c732f6d61737465722f646f63732f696d672f6368617274616c6c2e706e67)

# Context
Pie charts, as implemented in django-chartmodels, are difficult to interpret for the following reasons:

- humans aren't adapted to easily compare area (i.e. geometrical area)
  - areas in pie charts are geometrically irregular - they have odd shapes and angles
- 3D extrusion of chart areas further distorts perception
  - i.e. slices in the front of the chart are larger due to their 3D form, while shapes in the back do not have the same visible extrusion
- pie chart labels are scattered around the chart, meaning our eyes need to move in a circle to read them
- scattered labels and data projecting outward at radial angles make it difficult to compare values
  - i.e. we have to memorize the labels and do 'mental comparisons'

Likewise, a table has the following downside(s)
- data values are scattered horizontally and vertically, making comparison difficult
- lack of visual encoding means we must do 'mental comparisons' (i.e. symbolic reasoning)

# Proposal
A bar chart would make it much easier on the viewer, for the following reasons:

- data values are aligned on a common axis, meaning a viewer has only to scan one direction
- data values are encodes using one dimension, length. Humans are adapted to compare length, or width, without conscious effort. This means people can interpret the chart before they are even consciously aware of the interpretation
  - length is among one of several [preattentive attributes of visual design](https://www.coursera.org/learn/dataviz-design/lecture/GkLfQ/pre-attentive-attributes-of-visualizations)
- further, values can be sorted from high-to-low on the chart axis, making interpretation even easier

# Resources
For further reading about data visualization in general, as well as expansive descriptions of the above principles, see the following:

- [Now You See It: Simple Visualization Techniques for Quantitative Analysis](https://www.perceptualedge.com/library.php#Books) by Stephen Few
- [The Visual Display of Quantitative Information](https://www.edwardtufte.com/tufte/books_vdqi) by Edward R. Tufte

**Comment by synw** [comment]
Actually there is an undocumented option to change the chart type via a GET parameter in the url: `?c=bar`. It is supposed to be connected to buttons in the ui: I will add and document the feature while rewriting the frontend #4 

Thanks a lot for your very precise explanations and the references. It is a very interesting field where I should get more theoretical knowledge. I'll try to find some online free material to start with when I have a bit of time

**Comment by brylie** [comment]
> I'll try to find some online free material to start with when I have a bit of time

Forgive me if this seems obvious, but check with your local librarian. Libraries are usually eager to acquire new books requested by their patrons. Additionally, there may be an inter-library loan system, where you could request one of the books from a regional library.

**Comment by synw** [comment]
Well, the fact is that I am in a place of the world where libraries are extremely rare and limited. I'll keep the references for when I'll be in place with decent libraries where I'll be able to order them.

Thanks a lot for sharing your expertise

[Edit]: special thanks for the coursera link, I did not know about it
