### ISSUE TITLE
Declare explicit dependency on django-chartflo

### ISSUE THREAD

**Issue by brylie** [synw/django-chartmodels#3]
As was discussed in the [django-chartflo roadmap issue](https://github.com/synw/django-chartflo/issues/3#issuecomment-323711988), this package should remain separate from django-chartflo. In order to use django-chartflo as a dependency, this chart should explicitly reference django-chartflo (e.g. in a requirements.txt).

Add a requirements.txt, or the equivalent for PIP packaging, that references django-chartflo as a dependency of this project.

**Comment by synw** [comment]
Added a requirements.txt file. Will add to setup.py when released
